### ISSUE TITLE
There still are some RPCs that use property id instead of the name for contracts

### ISSUE THREAD

**Issue by Galuf1** [BlockPo/BlockPo-to-Tradelayer#197]
at least i know that tl_getposition uses the number of property id, for consistency most of the other RPCs that link to contracts use the name of the contract.

**Comment by patrickdugan** [comment]
Ok but should not these be interchangeable? Maybe it's easier for users to
get the RPC info for all contracts and pull up the relevant property ID?
Where are the strings for these contract aliases listed?

**Comment by Galuf1** [comment]
When we did the change it was because of series of futures, specifically when you needed to roll automatically with pegged currencies, you needed to jump internally a position in let's say LTCH20 to LTCJ20, so it was always better to search for the contract code, since for example this 2 contract could perfectly be property id 25, and 43. 

But i agree, it would be easier like that, maybe when we re do the property id system that's causing this problem of not having 2 sequential contracts having sequential property ids

**Comment by Galuf1** [comment]
The strings are in the database, it's under the "name" if i remember correctly

**Comment by patrickdugan** [comment]
As long as both the unpredictably assigned property id and the more
predictable codes are in the JSON of all contracts and thus wallet code
etc. can loop through it and decipher, it's fine.

For Oracle contract it's not clear how the automatic code system would
follow. It makes sense for Native futures because those are limited in
quantity. I think Oracle admins would have to manually issue new futures
periodically (presumably from the same address) and this would be something
I can provide support for in .js that we open source for these enterprise
users.

**Comment by Galuf1** [comment]
@santos177 RPC tl_closeposition has a TODO of checking if there is matching orders to close your position   https://github.com/BlockPo/BlockPo-to-Tradelayer/blob/9e543cfea202a4125488384bbfd1f42d69ab953b/src/tradelayer/rpctx.cpp#L1115

**Comment by Galuf1** [comment]
@santos177 RPC tl_getcache does't parse the address argument 
![image](https://user-images.githubusercontent.com/31936063/76110188-d1688600-5fbc-11ea-8867-6aecbbb4a824.png)

**Comment by santos177** [comment]
@Galuf1  tl_getcache rpc is fixed now : #198

**Comment by santos177** [comment]
@Galuf1 RPC tl_closeposition fixed in #200

**Comment by santos177** [comment]
Closing for now. If we need contractId instead of the name , we can modify it.
