### ISSUE TITLE
Payload RPC for Oracle Backup Restore

### ISSUE THREAD

**Issue by patrickdugan** [BlockPo/BlockPo-to-Tradelayer#242]
Not sure if we already have this tx logic and the vanilla rpc done but we'll need to include this so back-ups can also be multisig.

**Comment by patrickdugan** [comment]
Here's how I handle it in the RPC wrapper:

tl.getpayload_oraclebackup = function(contractTitle){
  //the reference address is the new backup, including if the backup address, now admin addess, is changed from being adming to some new address
  //even then the reference address here is still the back-up. The usage of hot vs. cold keys applies here: admin can be hot, back-ups are always cold.
  client.cmd('tl_createpayload_oraclebackup', contractTitle, function(err,data,resHeaders){
      if(err == null){
        return cb(data)
      }else{return err}
   })
}

**Comment by santos177** [comment]
@patrickdugan :please see rpc  tl_createpayload_change_oracleref ( in the future im gonna call this:  tl_createpayload_change_oracleadm).  You must send this from the actual admin address in order to change it. (more info here : https://github.com/BlockPo/BlockPo-to-Tradelayer/blob/master/src/tradelayer/rpcpayload.cpp#L978)
