### ISSUE TITLE
Err in send_vesting payload RPC

### ISSUE THREAD

**Issue by patrickdugan** [BlockPo/BlockPo-to-Tradelayer#389]
![send_vestingErr](https://user-images.githubusercontent.com/2466053/96925152-1d076b80-148a-11eb-9b32-87b78e8da989.png)

Not sure why but inputting technically correct parameters in this RPC gives me an error.

**Comment by patrickdugan** [comment]
@sinetek - if you'd like to investigate this, could help us ship a bit sooner.

**Comment by sinetek** [comment]
> @sinetek - if you'd like to investigate this, could help us ship a bit sooner.

sorry for the late reply, I am investigating.

**Comment by sinetek** [comment]
@patrickdugan 

I isolated the issue, we're doing our own parsing so we should get the string value via "getValStr" and not try to ask the parameter as a string type, which fails because in many cases the type first returns as a number. Or the other way, perhaps call write() and then use the string.

Now, would you say that this is the proper format?

```
                      "\nArguments:\n"
                      "1. amount               (string, required) the amount of vesting tokens to send\n"
```

or do we need the full 5 parameters
```
tl_createpayload_sendvesting \"fromaddress\" \"toaddress\" propertyid \"amount\" ( \"referenceamount\" )\n"
```

Additionally, I see a floating point error when quitting sometimes, I don't now if this is related to the parsing, or what.
```
$ ./src/qt/litecoin-qt 
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
Floating point exception
```

**Comment by sinetek** [comment]
The floating point exception is unrelated, I'll investigate furthur.

**Comment by santos177** [comment]
Hey @patrickdugan  it was my mistake: The rpc info is wrong, because for that payload we need just the amount of vesting tokens. I'm fixing it on vesting_fix branch!

**Comment by sinetek** [comment]
@santos177 The fix wouldn't be complete as is, unless I'm missing something, you also need to like:

```C++
    // obtain parameters & info
    auto p0 = request.params[0].write();
    int64_t amount = ParseAmount(p0, (bool)true);
```

to get the string as a string, otherwise it will bomb trying to parse it.

**Comment by santos177** [comment]
@sinetek please watch the file rpcpayload.cpp in folder src/tradelayer  in branch development.
